# Generated by Django 3.2.7 on 2021-09-20 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0004_auto_20210919_0931'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='set_goal',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
