# Generated by Django 3.2.7 on 2021-09-20 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0005_question_set_goal'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='set_goal',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
