# Generated by Django 2.0.1 on 2021-09-19 03:52

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import documents.models
import documents.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organisations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_name', models.CharField(max_length=100)),
                ('document_description', models.TextField()),
                ('document', models.FileField(upload_to=documents.models.upload_file_path, validators=[documents.validators.validate_file_size])),
                ('doc_type', models.CharField(choices=[('public', 'public'), ('private', 'private')], max_length=7, null=True)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_on', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='PrivateAccess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('access_tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ten', to='organisations.Tenant')),
                ('doc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='docu', to='documents.Document')),
            ],
        ),
    ]
