from django.urls import path
from . import views
urlpatterns = [
    path('', views.user_login, name='user-login'),
    path('user-logout/', views.user_logout, name='user-logout'),
    path('admin-dashboard/', views.admin_dashboard, name='admin-dashboard'),
    path('setlang/', views.set_language, name="set_language"),
    path('user-detail/', views.users_detail, name="user-detail"),
    path('organization/', views.organizations, name="organization"),
    path('stakeholder/', views.stakeholders, name="stakeholder"),
    path('question/', views.questions, name="question"),
    path('profile/', views.user_profile, name='profile'),
    path('profile-update/', views.user_profile_update, name='profile-update'),
    path('create-user/', views.create_user, name="create-user"),
    path('user-detail/edit/<int:pk>', views.update_user, name="edit-user"),
    path('delete-user/<int:pk>', views.delete_user, name="delete-user"),
    ##### User URL's #########
    path('dashboard/', views.user_dashboard, name='dashboard'),
    path('status/', views.data_status, name='data-status'),
    path('add-data/', views.add_data, name='add-data'),
    path('save-answer/<int:id>/', views.save_answer, name='save-answer'),
    path('save-answer-goal/<int:id>/',
         views.save_answer_goal, name='save-answer-goal'),
    path('save_single_answer/<int:id>/',
         views.save_single_answer, name='save_single_answer'),
    path('review-data/', views.review_data, name='review-data'),
    path('display-data/<int:id>/', views.display_data, name='display-data'),
    path('report/', views.report, name='report'),
    path('todos/', views.todos, name='todos'),
    path('goals-kpi/', views.goals_and_kpi, name='goals-kpi'),
    path('remove-goals/<int:goal_id>', views.remove_goal, name='remove-goal'),
    path('getcategories/', views.getcategories, name='getcategories'),
    path('getsubcategories/', views.getsubcategories, name='getsubcategories'),
    path('save_optional_answer/<int:id>/',
         views.save_optional_answer, name='save_optional_answer'),
    path('single_answer_attempt/<int:id>/',
         views.single_answer_attempt, name='single_answer_attempt'),
    path('changelanguage/<str:ln>/',
         views.changeLanguage, name='change_language'),
    path(r'^changelanguagelogin/<str:ln>/$',
         views.changeLanguageLogin, name='change_language_login'),
    path('downloadreport/<int:id>', views.download_report, name='download_report')
]
