# Generated by Django 2.0.1 on 2021-09-19 03:52

from django.db import migrations, models
import django.utils.timezone
import organisations.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organisation_name', models.CharField(max_length=100)),
                ('website_url', models.CharField(max_length=200, null=True)),
                ('organization_logo', models.ImageField(blank=True, null=True, upload_to=organisations.models.upload_image_path)),
                ('organization_address', models.CharField(max_length=100, null=True)),
                ('organisation_size', models.CharField(choices=[('0 - 10', '0 - 10'), ('10 - 50', '10 - 50'), ('50 - 200', '50 - 200'), ('200 - 500', '200 - 500'), ('500+', '500+')], default='0 - 10', max_length=50)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_on', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Organisation Details',
                'verbose_name_plural': 'Organisation Details',
            },
        ),
    ]
